variables:
  FF_USE_FASTZIP: 1
  COMPOSER_CACHE_DIR: ${CI_PROJECT_DIR}/.composer-cache

default:
  image: gitlab.jtl-software.com:4567/connector/connector-utils/ci-docker/php/cli:7.4
  tags:
    - docker
  before_script:
    - composer update --no-interaction --no-progress
  cache:
    key: vendor
    paths:
      - vendor
      - .composer-cache
      - composer.lock

include:
  - project: 'connector/connector-utils/CI-Templates'
    file:
      - 'auto-create-mr/ci.yaml'
      - 'code-quality/ci.yaml'

stages:
  - createMR
  - test
  - build

code_quality:
  before_script: []

test:unit:
  parallel:
    matrix:
      - BASE: 'php'
        VERSION: [ '7.1','7.2','7.3','7.4' ]
  image: gitlab.jtl-software.com:4567/tplatzke/docker-lamp/cli:${VERSION}
  stage: test
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --bootstrap vendor/autoload.php --log-junit junit.xml
  artifacts:
    reports:
      junit: junit.xml

build:
  stage: build
  variables:
    VERSION: dev
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: $CI_COMMIT_TAG
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: on_success
  script:
    - composer update --no-dev --optimize-autoloader --no-progress
    - php ./phing.phar release -Dversion=${VERSION}
  artifacts:
    expose_as: 'build'
    paths:
      - woo-jtl-connector-${VERSION}.zip
    expire_in: 2 days
