variables:
  FF_USE_FASTZIP: 1
  COMPOSER_CACHE_DIR: ${CI_PROJECT_DIR}/.composer-cache

default:
  image: gitlab.jtl-software.com:4567/tplatzke/docker-lamp/cli:7.4
  tags:
    - docker
  before_script:
    - composer update --no-interaction --no-progress
  cache:
    key: vendor
    policy: pull
    paths:
      - vendor
      - .composer-cache
      - composer.lock

include:
  - project: 'connector/connector-utils/php-code-quality'
    file: 'ci.yaml'

stages:
  - cache
  - test
  - build

build_cache:
  stage: cache
  script:
    - echo
  cache:
    key: vendor
    policy: pull-push
    paths:
      - vendor
      - .composer-cache
      - composer.lock

code_quality:
  before_script: []

test:unit:
  parallel:
    matrix:
      - BASE: 'php'
        VERSION: [ '7.1','7.2','7.3','7.4','8.0' ]
  image: gitlab.jtl-software.com:4567/tplatzke/docker-lamp/cli:${VERSION}
  stage: test
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --bootstrap vendor/autoload.php --log-junit junit.xml
  artifacts:
    reports:
      junit: junit.xml

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - composer update --no-dev --optimize-autoloader --no-progress
    - php ./phing.phar release -Dversion=${CI_COMMIT_TAG}
  artifacts:
    paths:
      - woo-jtl-connector-${CI_COMMIT_TAG}.zip
